name: fastai_env
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - ipykernel
  - jupyter
  - matplotlib
  - datasets
  - pandas
  - pip
  - scikit-learn
  - torchvision
  - pip:
    - fastai